language: ruby
before_install: 
  - gem install bundler
  - gem update --system
bundler_args: --without documentation production
rvm:
  - 2.0.0
before_script:
  - ./config/setup_config.sh
script:
  - 'RAILS_ENV=test rake spec'
  #- 'RAILS_ENV=test bundle exec guard-jasmine
services: 
  - mongodb